
  CREATE TABLE "CIECIA" 
   (	"ID_CIECIA" NUMBER, 
	"ID_BLATU" NUMBER, 
	"POZYCJA_X" FLOAT(5) NOT NULL ENABLE, 
	"POZYCJA_Y" FLOAT(5) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_CIECIA")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CIECIA" ADD CONSTRAINT "CIECIA_SUROWCE_FK" FOREIGN KEY ("ID_BLATU")
	  REFERENCES "SUROWCE" ("ID_BLATU") ENABLE;