
  CREATE TABLE "POZYCJE_OCZEKUJACE" 
   (	"ID_POZYCJI_OCZEKUJACEJ" NUMBER, 
	"ID_KLIENTA" NUMBER, 
	"ILOSC" NUMBER, 
	"DLUGOSC" FLOAT(126), 
	"SZEROKOSC" FLOAT(126), 
	"TERMIN_REALIZACJI" DATE, 
	"WYKONANO" NUMBER
   ) ;