
  CREATE TABLE "SUROWCE" 
   (	"ID_BLATU" NUMBER, 
	"DLUGOSC" NUMBER(5,0) NOT NULL ENABLE, 
	"SZEROKOSC" NUMBER(5,0) NOT NULL ENABLE, 
	"ILOSC" NUMBER NOT NULL ENABLE, 
	"MAGAZYNOWANY" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_BLATU")
  USING INDEX  ENABLE
   ) ;